[workspace]
authors = ["Ckrvxr <85326108+Ckrvxr@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "ppg_max30100_cnn_beats"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
train    = { cmd = "python code/train.py", env = { KMP_DUPLICATE_LIB_OK = "TRUE" } }
verify   = { cmd = "python code/verify.py", env = { KMP_DUPLICATE_LIB_OK = "TRUE" } }
prelabel = { cmd = "python code/prelabel.py" }
label    = { cmd = "python code/label_tool.py" }

[dependencies]
numpy = ">=2.4.6,<3"
pandas = ">=3.0.3,<4"
scipy = ">=1.17.1,<2"
matplotlib = ">=3.10.9,<4"
onnxruntime = ">=1.26.0,<2"

[pypi-dependencies]
torch = ">=2.12.0, <3"
scikit-learn = ">=1.8.0, <2"
